import { Hotel, Review, User } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john@example.com',
    mobile: '+1 234 567 8900',
    location: 'New York, USA',
    role: 'user',
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    mobile: '+1 234 567 8901',
    location: 'Los Angeles, USA',
    role: 'user',
  },
  {
    id: '3',
    name: 'Admin User',
    email: 'admin@staywise.com',
    mobile: '+1 234 567 8902',
    role: 'admin',
  },
];

export const mockHotels: Hotel[] = [
  {
    id: '1',
    name: 'The Grand Palace Hotel',
    location: 'Paris, France',
    description: 'Experience luxury in the heart of Paris with stunning views of the Eiffel Tower. Our hotel offers world-class amenities, Michelin-starred dining, and impeccable service.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    rating: 4.8,
    reviewCount: 324,
    amenities: ['Spa', 'Pool', 'Restaurant', 'Gym', 'Concierge'],
    aiSummary: 'Guests consistently praise the exceptional location and breathtaking views. The staff receives outstanding reviews for their attentive service.',
    aiHighlights: ['Prime location near Eiffel Tower', 'Exceptional staff service', 'Stunning rooftop restaurant', 'Luxurious spa facilities'],
    aiSentiment: 'positive',
  },
  {
    id: '2',
    name: 'Oceanview Resort & Spa',
    location: 'Maldives',
    description: 'A tropical paradise with overwater bungalows, crystal-clear waters, and pristine beaches. Perfect for romantic getaways and relaxation.',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    rating: 4.9,
    reviewCount: 512,
    amenities: ['Private Beach', 'Diving', 'Spa', 'Water Sports', 'Butler Service'],
    aiSummary: 'An exceptional luxury destination. Reviews highlight the privacy, stunning natural beauty, and world-class diving experiences.',
    aiHighlights: ['Overwater bungalows with glass floors', 'House reef snorkeling', 'Personalized butler service', 'Sunset dolphin cruises'],
    aiSentiment: 'positive',
  },
  {
    id: '3',
    name: 'Urban Boutique Hotel',
    location: 'Tokyo, Japan',
    description: 'A modern boutique hotel blending traditional Japanese aesthetics with contemporary comfort. Located in the vibrant Shibuya district.',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
    rating: 4.6,
    reviewCount: 289,
    amenities: ['Onsen', 'Rooftop Bar', 'Tea Ceremony', 'Concierge', 'Bike Rental'],
    aiSummary: 'Travelers love the perfect blend of traditional and modern. The location and unique cultural experiences receive top marks.',
    aiHighlights: ['Traditional onsen experience', 'Steps from Shibuya crossing', 'Authentic tea ceremony', 'Exceptional breakfast'],
    aiSentiment: 'positive',
  },
  {
    id: '4',
    name: 'Mountain Lodge Retreat',
    location: 'Swiss Alps',
    description: 'A cozy alpine retreat offering ski-in/ski-out access, gourmet cuisine, and breathtaking mountain views. Perfect for adventure seekers.',
    image: 'https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=800&q=80',
    rating: 4.7,
    reviewCount: 198,
    amenities: ['Ski Access', 'Fireplace', 'Restaurant', 'Spa', 'Guided Tours'],
    aiSummary: 'Ideal for winter sports enthusiasts. Guests rave about the ski-in/ski-out convenience and cozy atmosphere.',
    aiHighlights: ['Direct ski slope access', 'Cozy fireside lounges', 'Fondue restaurant', 'Mountain guide services'],
    aiSentiment: 'positive',
  },
  {
    id: '5',
    name: 'Desert Oasis Resort',
    location: 'Dubai, UAE',
    description: 'An architectural marvel in the desert featuring private pools, world-class dining, and authentic Arabian hospitality.',
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    rating: 4.5,
    reviewCount: 445,
    amenities: ['Private Pool', 'Desert Safari', 'Spa', 'Golf', 'Fine Dining'],
    aiSummary: 'A luxurious escape with exceptional amenities. Some guests note the remote location, but most find it part of the charm.',
    aiHighlights: ['Private infinity pools', 'Sunset desert safaris', 'Award-winning spa', 'Camel trekking experiences'],
    aiSentiment: 'positive',
  },
  {
    id: '6',
    name: 'Historic Castle Hotel',
    location: 'Edinburgh, Scotland',
    description: 'Stay in a beautifully restored 16th-century castle with modern amenities. Experience Scottish heritage at its finest.',
    image: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800&q=80',
    rating: 4.4,
    reviewCount: 156,
    amenities: ['Historic Tours', 'Whisky Bar', 'Gardens', 'Restaurant', 'Library'],
    aiSummary: 'Perfect for history enthusiasts. The authentic castle atmosphere delights guests, though some note the older infrastructure.',
    aiHighlights: ['Authentic medieval architecture', 'Extensive whisky collection', 'Beautiful formal gardens', 'Ghost tour experiences'],
    aiSentiment: 'neutral',
  },
];

export const mockReviews: Review[] = [
  {
    id: '1',
    hotelId: '1',
    hotelName: 'The Grand Palace Hotel',
    userId: '1',
    userName: 'John Doe',
    rating: 5,
    comment: 'Absolutely stunning hotel! The view of the Eiffel Tower from our room was magical. Staff went above and beyond.',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    hotelId: '1',
    hotelName: 'The Grand Palace Hotel',
    userId: '2',
    userName: 'Jane Smith',
    rating: 4,
    comment: 'Beautiful hotel with excellent location. The spa was incredible. Only minor issue was slow room service.',
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    hotelId: '2',
    hotelName: 'Oceanview Resort & Spa',
    userId: '1',
    userName: 'John Doe',
    rating: 5,
    comment: 'Paradise on Earth! The overwater bungalow exceeded all expectations. Perfect honeymoon destination.',
    createdAt: '2024-02-20',
  },
  {
    id: '4',
    hotelId: '3',
    hotelName: 'Urban Boutique Hotel',
    userId: '2',
    userName: 'Jane Smith',
    rating: 5,
    comment: 'Perfect blend of traditional and modern. The onsen was amazing and the location cannot be beat!',
    createdAt: '2024-02-18',
  },
  {
    id: '5',
    hotelId: '4',
    hotelName: 'Mountain Lodge Retreat',
    userId: '1',
    userName: 'John Doe',
    rating: 4,
    comment: 'Great ski-in/ski-out access. The fondue restaurant was delicious. Would definitely return!',
    createdAt: '2024-01-25',
  },
];

export const currentUser: User = mockUsers[0];
